package datasource;

import java.sql.*;

public interface DBConnection {
    void startTransaction() throws SQLException;
    Savepoint setSavepoint() throws SQLException;
    void commitTransaction() throws SQLException;
    void rollbackTransaction() throws SQLException;
    void rollbackTransaction(Savepoint savepoint) throws SQLException;
    Connection getConnection();
    PreparedStatement prepareStatement(String sql) throws SQLException;
    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;
    CallableStatement prepareCall(String sql) throws SQLException;
    void disconnect() throws SQLException;
    void setOnRelease(Runnable runnable);
    void release();
}
